# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnTIVUW8JKLW46nER4c-LRO0wJDtZ-3C

#Calculadora 2.0

##Boas Vindas
"""

print("Você está acessando a calculadora inteligente 2.0.") # Introdução à calculadora
nome_usuario = input("Para começar digite seu nome: " ) # Solicitação de nome
print("Seja bem vindo:",nome_usuario) # Mensagem ao usuário

"""## Inserção dos Números"""

print("Vamos ao cálculo, lembrando que é necessário colocar as casas decimais separadas por '.'") # Orientações ao usuário
num_1 = float(input("Insira aqui o primeiro número da operação: ")) # Usuário insere primeiro número
num_2 = float(input("Insira aqui o segundo número da operação: ")) # Usuário insere segundo número
números = [num_1, num_2] # Cria a lista números
print("Seus números são:", números)

"""## Operações Matemáticas"""

soma = num_1 + num_2 # Cria a variável soma
subtração = num_1 - num_2 # Cria a variável subtração
multiplicação = num_1 * num_2 # Cria a variável multiplicação
divisão = num_1 / num_2 # Cria a variável divisão
divisão_inteira = num_1 // num_2 # Cria a variável divisão inteira
potenciação = num_1 ** num_2 # Cria a variável potenciação
print("A soma dos números é:", soma) # Soma os valores
print("A subtração dos números é:", subtração) # Subtrai os valores
print("A multiplicação dos números é:", multiplicação) # Multiplica os valores
print("A divisão dos números é:", divisão) # Divide os valores
print("A divisão inteira dos números é:", divisão_inteira) # Informa a divisão inteira
print("A potenciação dos números é:", potenciação) # Informa a potenciação

"""## Condicional"""

# Exemplo de condicional
if soma >= 100:
  print("Soma maior ou igual a 100")
else:
 print("Soma menor do que 100")

"""## Laço de Repetição"""

# Exemplo de laço de repetição
for i, número in enumerate(números):
  print(f"O índice do número é {i}, seu valor é {número} e sua ordem de inserção no programa foi {i + 1}º")